# Generated by Django 4.2 on 2024-04-02 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('webapp', '0004_delete_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
                ('test_no', models.IntegerField()),
                ('test_avg', models.IntegerField()),
                ('auth', models.CharField(choices=[('accepted', 'accepted'), ('Packed', 'packed'), ('on the way', 'on the way'), ('deleverd', 'deleverd'), ('pending', 'Pending')], max_length=20)),
            ],
        ),
    ]
