# Generated by Django 4.2 on 2024-04-03 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_test_questions_alter_student_auth'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
