# Generated by Django 4.2 on 2024-04-03 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
