# Generated by Django 4.2 on 2024-04-03 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test_questions',
        ),
    ]
