# Generated by Django 4.2 on 2024-04-03 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_delete_test_questions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test_questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('a', models.CharField(max_length=500)),
                ('b', models.CharField(max_length=500)),
                ('c', models.CharField(max_length=500)),
                ('d', models.CharField(max_length=500)),
                ('ans', models.CharField(max_length=1)),
            ],
        ),
    ]
